### ISSUE TITLE
Can I use your pre-trained models with FPS 24/25?

### ISSUE THREAD

**Issue by sujoyrc** [enesduran/HMP#2]
I want to use your pretrained models for my research. However my in-the-wild videos are of FPS 24 and FPS25. Can I use your model if I update the FPS in the yaml file?

**Comment by enesduran** [comment]
Hey,
We use a NEMF-based prior which can work under motions with different framerates. This is a legacy from NEMF thanks to their motion prior formulation

**Comment by sujoyrc** [comment]
Thank you. However the download script uses 

./data/amass/generative/mean-neutral-128-30fps.pt
./data/amass/generative/std-neutral-128-30fps.pt

Do I need a different for running on 24 fps?

**Comment by enesduran** [comment]
Hey, ideally yes. The motion datasets needs to be processed in the FPS of your setting (24 for your case AFAIU) and then compute mean and std based on  [this.](https://github.com/enesduran/HMP/blob/main/src/datasets/amass.py#L795) 

However, just naively trying the mean and std values for 30fps case for would be a good starting point. I would expect std to be a bit less than 30 fps case but it may work as well.
