### ISSUE TITLE
evaluation introduction missing

### ISSUE THREAD

**Issue by linjiangya** [enesduran/HMP#4]
Dear authors,

Thanks for your great work. I was wondering if it's possible to provide the introduction for evaluation. For example, I didn't find the  'gt_data' needed for 'src/evaluation.py' during downloading:
https://github.com/enesduran/HMP/blob/0361b22080cc4a4b0ad25167dd329b13925ae598/src/evaluation.py#L425

**Comment by enesduran** [comment]
src/evaluatuon.py is a legacy script fikle from NeMF baseline. We do not use it. This evaluation.py script provides visualization of different body motion priors. You can refer to NeMF repository for it.
