### ISSUE TITLE
Question on Hard-coded Focal Length

### ISSUE THREAD

**Issue by ShenghaoZhou** [enesduran/HMP#5]
Thanks for your great work! I notice camera focal length is hard coded as 5000 in the code. I wonder if there is any reason for this magic number.

**Comment by enesduran** [comment]
Thank you for your interest in our work. For in-the-wild setting we indeed assumed camera intrinsics. For ITW settings 5000 is generally used. You can well change this value. Couple of important points here:
1) We have to make sure that weak perspective projection assumption holds.  
2) It has been shown that overestimation of focal length hurts less than underestimation [https://arxiv.org/pdf/2110.00620](https://arxiv.org/pdf/2110.00620)
3) You can well use an off-the-shelf method that predicts the camera intrinsics. The work I sent does this as well. 

Best

**Comment by ShenghaoZhou** [comment]
Thanks for the explanation and insight!
